//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceView
    {
        public System.Guid ConferenceID { get; set; }
        public Nullable<System.Guid> SubjectID { get; set; }
        public string SubjectName { get; set; }
        public string ConferenceName { get; set; }
        public string ConferenceDetails { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartDate_Str { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string ImageName { get; set; }
        public string Url { get; set; }
        public int NoView { get; set; }
        public bool IsBlock { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreateUser_FullName { get; set; }
        public string ModifyUser_FullName { get; set; }
    }
}
