//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditoralBoard
    {
        public System.Guid PersionID { get; set; }
        public System.Guid JournalID { get; set; }
        public string PersonName { get; set; }
        public string Affiliation { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public System.Guid PositionID { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual EditorBoardPosition EditorBoardPosition { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
