//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestEditor
    {
        public System.Guid GuestEditorID { get; set; }
        public System.Guid AuthorID { get; set; }
        public System.Guid JournalVersionID { get; set; }
    
        public virtual JournalVersion JournalVersion { get; set; }
        public virtual Author Author { get; set; }
    }
}
