//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalView
    {
        public System.Guid JournalID { get; set; }
        public System.Guid SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<System.Guid> PublishPeriodID { get; set; }
        public string PublishPeriodName { get; set; }
        public string JournalName { get; set; }
        public string ImagePath { get; set; }
        public string BannerPath { get; set; }
        public int NoView { get; set; }
        public Nullable<double> ImpactFactor { get; set; }
        public string About { get; set; }
        public string AimsScope { get; set; }
        public string ArticleProcessingCharge { get; set; }
        public string PublicationEthics { get; set; }
        public string ShortcutCharacter { get; set; }
        public string EditorialBoard { get; set; }
        public string AuthorGuidlines { get; set; }
        public string OpenSpecialIssues { get; set; }
        public string SpecialIssuesGuidlines { get; set; }
        public string ReviewersAcknowledgment { get; set; }
        public string ConderencePublication { get; set; }
        public string PrintISSN { get; set; }
        public string OnlineISSN { get; set; }
        public int YearIssue { get; set; }
        public bool IsBlock { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string CreateUser_FullName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public string ModifyUser_FullName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
