//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.EditoralBoard = new HashSet<EditoralBoard>();
            this.EmailAlert = new HashSet<EmailAlert>();
            this.JournalReviewer = new HashSet<JournalReviewer>();
            this.JournalScope = new HashSet<JournalScope>();
            this.JournalSponsor = new HashSet<JournalSponsor>();
            this.OpenSpecialIssue = new HashSet<OpenSpecialIssue>();
            this.RelationalJournal = new HashSet<RelationalJournal>();
            this.JournalVersion = new HashSet<JournalVersion>();
            this.ManuscriptCharge = new HashSet<ManuscriptCharge>();
        }
    
        public System.Guid JournalID { get; set; }
        public System.Guid SubjectID { get; set; }
        public Nullable<System.Guid> PublishPeriodID { get; set; }
        public string JournalName { get; set; }
        public string ImagePath { get; set; }
        public string BannerPath { get; set; }
        public int NoView { get; set; }
        public Nullable<double> ImpactFactor { get; set; }
        public string About { get; set; }
        public string AimsScope { get; set; }
        public string ArticleProcessingCharge { get; set; }
        public string PublicationEthics { get; set; }
        public string ShortcutCharacter { get; set; }
        public string EditorialBoard { get; set; }
        public string AuthorGuidlines { get; set; }
        public string OpenSpecialIssues { get; set; }
        public string SpecialIssuesGuidlines { get; set; }
        public string ReviewersAcknowledgment { get; set; }
        public string ConderencePublication { get; set; }
        public string PrintISSN { get; set; }
        public string OnlineISSN { get; set; }
        public int YearIssue { get; set; }
        public bool IsBlock { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditoralBoard> EditoralBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAlert> EmailAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalReviewer> JournalReviewer { get; set; }
        public virtual PublishPeriod PublishPeriod { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalScope> JournalScope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalSponsor> JournalSponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenSpecialIssue> OpenSpecialIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationalJournal> RelationalJournal { get; set; }
        public virtual RelationalJournal RelationalJournal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalVersion> JournalVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManuscriptCharge> ManuscriptCharge { get; set; }
    }
}
