//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptUser
    {
        public System.Guid ManuscriptUserID { get; set; }
        public System.Guid ManuscriptID { get; set; }
        public System.Guid UserId { get; set; }
        public bool Correspond { get; set; }
    
        public virtual Manuscript Manuscript { get; set; }
    }
}
