//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptAuthor
    {
        public System.Guid AuthorID { get; set; }
        public System.Guid ManuscriptID { get; set; }
        public string AuthorTitle { get; set; }
        public string AuthorFullName { get; set; }
        public string AuthorEmail { get; set; }
        public string Affiliation { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public bool CorrespondingAuthor { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Manuscript Manuscript { get; set; }
    }
}
