//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manuscript
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manuscript()
        {
            this.ConferenceManuscript = new HashSet<ConferenceManuscript>();
            this.ManuscriptPhase = new HashSet<ManuscriptPhase>();
            this.ManuscriptUser = new HashSet<ManuscriptUser>();
            this.ManuscriptAuthor = new HashSet<ManuscriptAuthor>();
        }
    
        public System.Guid ManuscriptID { get; set; }
        public string ManuscriptTitle { get; set; }
        public string @abstract { get; set; }
        public string coverLetterPath { get; set; }
        public System.Guid ManuscriptTypeID { get; set; }
        public System.Guid JournalID { get; set; }
        public string FilePath { get; set; }
        public System.Guid JournalVolumeTypeID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string ManuscriptStatusID { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> NoView { get; set; }
        public string ReferenceNumber { get; set; }
        public string AllAuthorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceManuscript> ConferenceManuscript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManuscriptPhase> ManuscriptPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManuscriptUser> ManuscriptUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManuscriptAuthor> ManuscriptAuthor { get; set; }
    }
}
