//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptView
    {
        public string AuthorFullName { get; set; }
        public string JournalName { get; set; }
        public string ManuscriptTitle { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public bool correspondingAuthor { get; set; }
    }
}
