//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptPhaseDecision
    {
        public System.Guid ManuscriptPhaseDecisionID { get; set; }
        public System.Guid ManuscriptPhaseID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> DecisionID { get; set; }
        public string Remarks { get; set; }
        public string RemarksFilePath { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual ManuscriptPhase ManuscriptPhase { get; set; }
    }
}
