//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManuscriptPhase()
        {
            this.ManuscriptPhaseDecision = new HashSet<ManuscriptPhaseDecision>();
        }
    
        public System.Guid ManuscriptPhaseID { get; set; }
        public System.Guid ManuscriptID { get; set; }
        public System.Guid ManuscriptStatusID { get; set; }
        public System.DateTime PhaseEntryDate { get; set; }
        public Nullable<System.DateTime> PhaseExitDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManuscriptPhaseDecision> ManuscriptPhaseDecision { get; set; }
        public virtual Manuscript Manuscript { get; set; }
    }
}
