//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishArticleScope
    {
        public System.Guid PublishedArticleScopeID { get; set; }
        public System.Guid PublishedArticleID { get; set; }
        public System.Guid ScopeID { get; set; }
        public bool IsBlock { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual PublishedArticle PublishedArticle { get; set; }
    }
}
