//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishedArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublishedArticle()
        {
            this.PublishArticleAuthor = new HashSet<PublishArticleAuthor>();
            this.PublishArticleScope = new HashSet<PublishArticleScope>();
        }
    
        public System.Guid PublishedArticleID { get; set; }
        public System.Guid JournalVersionID { get; set; }
        public System.Guid ArticleTypeID { get; set; }
        public string ArticleTitle { get; set; }
        public string Abstract { get; set; }
        public string ArticleContent { get; set; }
        public int NoView { get; set; }
        public string FilePath { get; set; }
        public System.DateTime RecievedDate { get; set; }
        public System.DateTime AcceptDate { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Url { get; set; }
        public Nullable<int> FromPage { get; set; }
        public Nullable<int> ToPage { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublishArticleAuthor> PublishArticleAuthor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublishArticleScope> PublishArticleScope { get; set; }
    }
}
