//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_ActionLog
    {
        public System.Guid LogID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Url { get; set; }
        public string Url_Referrer { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string View { get; set; }
        public string RemoteAddress { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
        public string UserID { get; set; }
        public string BrowserID { get; set; }
        public string BrowserVersion { get; set; }
        public Nullable<bool> BrowserIsMobileDevice { get; set; }
        public string Cookies { get; set; }
        public string HttpMethod { get; set; }
        public string host { get; set; }
        public string ContentType { get; set; }
        public string ContentLenght { get; set; }
    }
}
