//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textroad.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public string CountryName { get; set; }
        public System.Guid UserTypeID { get; set; }
        public string UserTypeName { get; set; }
        public bool Active { get; set; }
        public bool AllowAccess { get; set; }
    }
}
