//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Administration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Administration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Administration", typeof(Administration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Date.
        /// </summary>
        public static string AcceptDate {
            get {
                return ResourceManager.GetString("AcceptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AimsScope.
        /// </summary>
        public static string AimsScope {
            get {
                return ResourceManager.GetString("AimsScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Content.
        /// </summary>
        public static string ArticleContent {
            get {
                return ResourceManager.GetString("ArticleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Processing Charge.
        /// </summary>
        public static string ArticleProcessingCharge {
            get {
                return ResourceManager.GetString("ArticleProcessingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Title.
        /// </summary>
        public static string ArticleTitle {
            get {
                return ResourceManager.GetString("ArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Type.
        /// </summary>
        public static string ArticleType {
            get {
                return ResourceManager.GetString("ArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Guidlines.
        /// </summary>
        public static string AuthorGuidlines {
            get {
                return ResourceManager.GetString("AuthorGuidlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conderence Publication.
        /// </summary>
        public static string ConderencePublication {
            get {
                return ResourceManager.GetString("ConderencePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        public static string Conference {
            get {
                return ResourceManager.GetString("Conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Details.
        /// </summary>
        public static string ConferenceDetails {
            get {
                return ResourceManager.GetString("ConferenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Name.
        /// </summary>
        public static string ConferenceName {
            get {
                return ResourceManager.GetString("ConferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corresponding.
        /// </summary>
        public static string Corresponding {
            get {
                return ResourceManager.GetString("Corresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Conference.
        /// </summary>
        public static string CreateConference {
            get {
                return ResourceManager.GetString("CreateConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Journal.
        /// </summary>
        public static string CreateJournal {
            get {
                return ResourceManager.GetString("CreateJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Journal Version.
        /// </summary>
        public static string CreateJournalVersion {
            get {
                return ResourceManager.GetString("CreateJournalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create News.
        /// </summary>
        public static string CreateNews {
            get {
                return ResourceManager.GetString("CreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Published Article.
        /// </summary>
        public static string CreatePublishedArticle {
            get {
                return ResourceManager.GetString("CreatePublishedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Conference.
        /// </summary>
        public static string EditConference {
            get {
                return ResourceManager.GetString("EditConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Journal.
        /// </summary>
        public static string EditJournal {
            get {
                return ResourceManager.GetString("EditJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Journal Version.
        /// </summary>
        public static string EditJournalVersion {
            get {
                return ResourceManager.GetString("EditJournalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit News.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial Board.
        /// </summary>
        public static string EditorialBoard {
            get {
                return ResourceManager.GetString("EditorialBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Page.
        /// </summary>
        public static string FromPage {
            get {
                return ResourceManager.GetString("FromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact Factor.
        /// </summary>
        public static string ImpactFactor {
            get {
                return ResourceManager.GetString("ImpactFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Name.
        /// </summary>
        public static string IssueName {
            get {
                return ResourceManager.GetString("IssueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Number.
        /// </summary>
        public static string IssueNumber {
            get {
                return ResourceManager.GetString("IssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Details.
        /// </summary>
        public static string JournalDetails {
            get {
                return ResourceManager.GetString("JournalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Name.
        /// </summary>
        public static string JournalName {
            get {
                return ResourceManager.GetString("JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Version.
        /// </summary>
        public static string JournalVersion {
            get {
                return ResourceManager.GetString("JournalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Version Details.
        /// </summary>
        public static string JournalVersionDetails {
            get {
                return ResourceManager.GetString("JournalVersionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Volume.
        /// </summary>
        public static string JournalVolume {
            get {
                return ResourceManager.GetString("JournalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Volume Type.
        /// </summary>
        public static string JournalVolumeType {
            get {
                return ResourceManager.GetString("JournalVolumeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Volume.
        /// </summary>
        public static string JournalVolumeTypeName {
            get {
                return ResourceManager.GetString("JournalVolumeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Conference.
        /// </summary>
        public static string NewConference {
            get {
                return ResourceManager.GetString("NewConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Journal.
        /// </summary>
        public static string NewJournal {
            get {
                return ResourceManager.GetString("NewJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Journal Version.
        /// </summary>
        public static string NewJournalVersion {
            get {
                return ResourceManager.GetString("NewJournalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New News.
        /// </summary>
        public static string NewNews {
            get {
                return ResourceManager.GetString("NewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Published Article.
        /// </summary>
        public static string NewPublishedArticle {
            get {
                return ResourceManager.GetString("NewPublishedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Details.
        /// </summary>
        public static string NewsDetails {
            get {
                return ResourceManager.GetString("NewsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Title.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Views.
        /// </summary>
        public static string NoView {
            get {
                return ResourceManager.GetString("NoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online ISSN.
        /// </summary>
        public static string OnlineISSN {
            get {
                return ResourceManager.GetString("OnlineISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Special Issues.
        /// </summary>
        public static string OpenSpecialIssues {
            get {
                return ResourceManager.GetString("OpenSpecialIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ISSN.
        /// </summary>
        public static string PrintISSN {
            get {
                return ResourceManager.GetString("PrintISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Ethics.
        /// </summary>
        public static string PublicationEthics {
            get {
                return ResourceManager.GetString("PublicationEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Article.
        /// </summary>
        public static string PublishedArticle {
            get {
                return ResourceManager.GetString("PublishedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Period.
        /// </summary>
        public static string PublishPeriod {
            get {
                return ResourceManager.GetString("PublishPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Publish Period.
        /// </summary>
        public static string PublishPeriodCreate {
            get {
                return ResourceManager.GetString("PublishPeriodCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PublishPeriodDescription {
            get {
                return ResourceManager.GetString("PublishPeriodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Period Details.
        /// </summary>
        public static string PublishPeriodDetails {
            get {
                return ResourceManager.GetString("PublishPeriodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Publish Period.
        /// </summary>
        public static string PublishPeriodEdit {
            get {
                return ResourceManager.GetString("PublishPeriodEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Period Name.
        /// </summary>
        public static string PublishPeriodName {
            get {
                return ResourceManager.GetString("PublishPeriodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Publish Period.
        /// </summary>
        public static string PublishPeriodNew {
            get {
                return ResourceManager.GetString("PublishPeriodNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved Date.
        /// </summary>
        public static string RecievedDate {
            get {
                return ResourceManager.GetString("RecievedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewers Acknowledgment.
        /// </summary>
        public static string ReviewersAcknowledgment {
            get {
                return ResourceManager.GetString("ReviewersAcknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Scope.
        /// </summary>
        public static string ScopeCreate {
            get {
                return ResourceManager.GetString("ScopeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ScopeDescription {
            get {
                return ResourceManager.GetString("ScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Details.
        /// </summary>
        public static string ScopeDetails {
            get {
                return ResourceManager.GetString("ScopeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Scope.
        /// </summary>
        public static string ScopeEdit {
            get {
                return ResourceManager.GetString("ScopeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scope.
        /// </summary>
        public static string ScopeNew {
            get {
                return ResourceManager.GetString("ScopeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string ShortcutCharacter {
            get {
                return ResourceManager.GetString("ShortcutCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Issues Guidlines.
        /// </summary>
        public static string SpecialIssuesGuidlines {
            get {
                return ResourceManager.GetString("SpecialIssuesGuidlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sponsor.
        /// </summary>
        public static string SponsorCreate {
            get {
                return ResourceManager.GetString("SponsorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Details.
        /// </summary>
        public static string SponsorDetails {
            get {
                return ResourceManager.GetString("SponsorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sponsor.
        /// </summary>
        public static string SponsorEdit {
            get {
                return ResourceManager.GetString("SponsorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SponsorImage {
            get {
                return ResourceManager.GetString("SponsorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Name.
        /// </summary>
        public static string SponsorName {
            get {
                return ResourceManager.GetString("SponsorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sponsor.
        /// </summary>
        public static string SponsorNew {
            get {
                return ResourceManager.GetString("SponsorNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string SponsorShortcut {
            get {
                return ResourceManager.GetString("SponsorShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subject.
        /// </summary>
        public static string SubjectCreate {
            get {
                return ResourceManager.GetString("SubjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjkect Details.
        /// </summary>
        public static string SubjectDetails {
            get {
                return ResourceManager.GetString("SubjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subject.
        /// </summary>
        public static string SubjectEdit {
            get {
                return ResourceManager.GetString("SubjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subject.
        /// </summary>
        public static string SubjectNew {
            get {
                return ResourceManager.GetString("SubjectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectTitle {
            get {
                return ResourceManager.GetString("SubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Page.
        /// </summary>
        public static string ToPage {
            get {
                return ResourceManager.GetString("ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Issue.
        /// </summary>
        public static string YearIssue {
            get {
                return ResourceManager.GetString("YearIssue", resourceCulture);
            }
        }
    }
}
