//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be active, please check your data and try again.
        /// </summary>
        public static string AlertActiveErrorMessage {
            get {
                return ResourceManager.GetString("AlertActiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been activated.
        /// </summary>
        public static string AlertActiveInfoMessage {
            get {
                return ResourceManager.GetString("AlertActiveInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been activated.
        /// </summary>
        public static string AlertActiveSuccessMessage {
            get {
                return ResourceManager.GetString("AlertActiveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be active.
        /// </summary>
        public static string AlertActiveWarningMessage {
            get {
                return ResourceManager.GetString("AlertActiveWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be added, please check your data and try again.
        /// </summary>
        public static string AlertAddErrorMessage {
            get {
                return ResourceManager.GetString("AlertAddErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been added.
        /// </summary>
        public static string AlertAddInfoMessage {
            get {
                return ResourceManager.GetString("AlertAddInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been added.
        /// </summary>
        public static string AlertAddSuccessMessage {
            get {
                return ResourceManager.GetString("AlertAddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be add.
        /// </summary>
        public static string AlertAddWarningMessage {
            get {
                return ResourceManager.GetString("AlertAddWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be deactive, please check your data and try again.
        /// </summary>
        public static string AlertDeactiveErrorMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deactivated.
        /// </summary>
        public static string AlertDeactiveInfoMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deatctivated.
        /// </summary>
        public static string AlertDeactiveSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be deactive.
        /// </summary>
        public static string AlertDeactiveWarningMessage {
            get {
                return ResourceManager.GetString("AlertDeactiveWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be delete, please check your data and try again.
        /// </summary>
        public static string AlertDeleteErrorMessage {
            get {
                return ResourceManager.GetString("AlertDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted.
        /// </summary>
        public static string AlertDeleteInfoMessage {
            get {
                return ResourceManager.GetString("AlertDeleteInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been deleted.
        /// </summary>
        public static string AlertDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be delete.
        /// </summary>
        public static string AlertDeleteWarningMessage {
            get {
                return ResourceManager.GetString("AlertDeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be update, please check your data and try again.
        /// </summary>
        public static string AlertEditErrorMessage {
            get {
                return ResourceManager.GetString("AlertEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been updated.
        /// </summary>
        public static string AlertEditInfoMessage {
            get {
                return ResourceManager.GetString("AlertEditInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been updated.
        /// </summary>
        public static string AlertEditSuccessMessage {
            get {
                return ResourceManager.GetString("AlertEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be update.
        /// </summary>
        public static string AlertEditWarningMessage {
            get {
                return ResourceManager.GetString("AlertEditWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be export, please try again.
        /// </summary>
        public static string AlertExportErrorMessage {
            get {
                return ResourceManager.GetString("AlertExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been exported.
        /// </summary>
        public static string AlertExportInfoMessage {
            get {
                return ResourceManager.GetString("AlertExportInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been exported.
        /// </summary>
        public static string AlertExportSuccessMessage {
            get {
                return ResourceManager.GetString("AlertExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be export.
        /// </summary>
        public static string AlertExportWarningMessage {
            get {
                return ResourceManager.GetString("AlertExportWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) failed to be import, please check your data and try again.
        /// </summary>
        public static string AlertImportErrorMessage {
            get {
                return ResourceManager.GetString("AlertImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been imported.
        /// </summary>
        public static string AlertImportInfoMessage {
            get {
                return ResourceManager.GetString("AlertImportInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) has been imported.
        /// </summary>
        public static string AlertImportSuccessMessage {
            get {
                return ResourceManager.GetString("AlertImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) will be import.
        /// </summary>
        public static string AlertImportWarningMessage {
            get {
                return ResourceManager.GetString("AlertImportWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info!.
        /// </summary>
        public static string AlertInfo {
            get {
                return ResourceManager.GetString("AlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string AlertLoginFailedErrorMessage {
            get {
                return ResourceManager.GetString("AlertLoginFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string AlertWarning {
            get {
                return ResourceManager.GetString("AlertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-active.
        /// </summary>
        public static string ButtonDeactive {
            get {
                return ResourceManager.GetString("ButtonDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create on.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by.
        /// </summary>
        public static string CreateUserFullNameEn {
            get {
                return ResourceManager.GetString("CreateUserFullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DeactivateConfirmActionButton {
            get {
                return ResourceManager.GetString("DeactivateConfirmActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeactivateConfirmCloseButton {
            get {
                return ResourceManager.GetString("DeactivateConfirmCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to deactivate selected item(s)?.
        /// </summary>
        public static string DeactivateConfirmDialogBody {
            get {
                return ResourceManager.GetString("DeactivateConfirmDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Confirm.
        /// </summary>
        public static string DeactivateConfirmDialogHeader {
            get {
                return ResourceManager.GetString("DeactivateConfirmDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DeleteConfirmActionButton {
            get {
                return ResourceManager.GetString("DeleteConfirmActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeleteConfirmCloseButton {
            get {
                return ResourceManager.GetString("DeleteConfirmCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected item(s)?.
        /// </summary>
        public static string DeleteConfirmDialogBody {
            get {
                return ResourceManager.GetString("DeleteConfirmDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string DeleteConfirmDialogHeader {
            get {
                return ResourceManager.GetString("DeleteConfirmDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all data as csv.
        /// </summary>
        public static string ExportAllDataCsv {
            get {
                return ResourceManager.GetString("ExportAllDataCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all data as pdf.
        /// </summary>
        public static string ExportAllDataPdf {
            get {
                return ResourceManager.GetString("ExportAllDataPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export visible data as csv.
        /// </summary>
        public static string ExportVisibleDataCsv {
            get {
                return ResourceManager.GetString("ExportVisibleDataCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export visible data as pdf.
        /// </summary>
        public static string ExportVisibleDataPdf {
            get {
                return ResourceManager.GetString("ExportVisibleDataPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string IsBlock {
            get {
                return ResourceManager.GetString("IsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading please wait.....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify on.
        /// </summary>
        public static string ModifyDateTime {
            get {
                return ResourceManager.GetString("ModifyDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify by .
        /// </summary>
        public static string ModifyUserFullNameEn {
            get {
                return ResourceManager.GetString("ModifyUserFullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatchValidationError {
            get {
                return ResourceManager.GetString("PasswordNotMatchValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string requiredFieldValidationMsg {
            get {
                return ResourceManager.GetString("requiredFieldValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Select ----.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up With Email.
        /// </summary>
        public static string SignUpWithEmail {
            get {
                return ResourceManager.GetString("SignUpWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
