//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityEntities : DbContext
    {
        public SecurityEntities()
            : base("name=SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessType> AccessType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleService> RoleService { get; set; }
        public virtual DbSet<RoleServiceAccess> RoleServiceAccess { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceAccess> ServiceAccess { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UserGroupRole> UserGroupRole { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserService> UserService { get; set; }
        public virtual DbSet<UserServiceAccess> UserServiceAccess { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<ServiceAccessView> ServiceAccessView { get; set; }
        public virtual DbSet<UserRoleServiceAccessView> UserRoleServiceAccessView { get; set; }
        public virtual DbSet<UserRoleView> UserRoleView { get; set; }
    }
}
