//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAccessView
    {
        public System.Guid ServiceAccessID { get; set; }
        public System.Guid ServiceID { get; set; }
        public string ServiceTag { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDescription { get; set; }
        public bool Service_IsBlock { get; set; }
        public System.Guid AccessTypeID { get; set; }
        public string AccessTypeName { get; set; }
        public bool AccessType_IsBlock { get; set; }
        public string ControlTag { get; set; }
        public bool ServiceAccess_IsBlock { get; set; }
    }
}
