//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleServiceAccessView
    {
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public System.Guid ServiceId { get; set; }
        public string ServiceTag { get; set; }
        public string ServiceName { get; set; }
        public System.Guid ServiceAccessId { get; set; }
        public System.Guid AccessTypeId { get; set; }
        public string ControlTag { get; set; }
    }
}
